### ISSUE TITLE
Questions Regarding Abnormal Inference Results Generated After Running Docker Container

### ISSUE THREAD

**Issue by zkan12** [MASILab/S-EFOV#2]
Dear developers,

Thank you for sharing this resource, and congratulations on the publication in Radiology!

I would like to take some of your time to address my questions. My concerns are as follows: I initially used a public dataset you mentioned and performed inference on certain images using Docker. However, I noticed an inversion along the y-axis (world coordinate system) when visualizing the images in itk-snap, compared to the output images in the report. At the same time, the predicted bounding box and segmentation results also appear unsatisfactory.

**The appearance of the original image in itk-snap is as follows:**
<img width="500" alt="a3b4ca30ab82899f27ba7859f5fee2c" src="https://github.com/MASILab/S-EFOV/assets/104334857/599b9fd1-6b72-4d73-8030-80cba0a702e1">

**The output result after performing inference on the original image:**
<img width="399" alt="image" src="https://github.com/MASILab/S-EFOV/assets/104334857/b074237c-8edb-4ee7-adf9-733ca0e63999">

I attempted to address this by using the "reorient image" tool in itk-snap to flip the y-axis. Although the final orientation in the report seems to be consistent with before, there was a significant improvement in the segmentation quality on the same image.

**The image after flipping the y-axis:**
<img width="1062" alt="image" src="https://github.com/MASILab/S-EFOV/assets/104334857/4ff926db-5a17-43eb-bc1c-bc11f2ad339c">

**The output result after performing inference**
<img width="377" alt="image" src="https://github.com/MASILab/S-EFOV/assets/104334857/673fa9fd-cca2-4c97-b314-1350e884e7ae">

In addition to performing inference on public datasets, I conducted tests on my private dataset. However, the results obtained still exhibit similar issues as before. I sincerely hope you can guide me on how to achieve results similar to the examples you published on GitHub or provide insights on avoiding low-quality segmentations.

**some results from testing on a private dataset:**
![eba21acfa150c440dfb25a5b5d6735f](https://github.com/MASILab/S-EFOV/assets/104334857/064612ff-9c4c-4f47-8381-eb1d10b96b97)
<img width="598" alt="35311d4c77402bd4e13b2c476155f30" src="https://github.com/MASILab/S-EFOV/assets/104334857/fabdeccb-fe47-4064-9f3a-348f58c6b487">

 **your typical result report obtained for a lung cancer screening CT:**
<img width="313" alt="image" src="https://github.com/MASILab/S-EFOV/assets/104334857/7bf3be84-db3f-407e-a169-11b0558cc017">

lastly，wish you a joyful life and smooth progress in your academic research!

**Comment by zkan12** [comment]
Thank you again for the developer's online assistance. The problem has been successfully resolved. We found that the issue stemmed from different preprocessing methods. When converting directly with itk-snap, the aforementioned error occurred, but using dcm2niix again for conversion resulted in the output being generated correctly.

**Comment by kwxu** [comment]
> Thank you again for the developer's online assistance. The problem has been successfully resolved. We found that the issue stemmed from different preprocessing methods. When converting directly with itk-snap, the aforementioned error occurred, but using dcm2niix again for conversion resulted in the output being generated correctly.

Hi!

Thanks for confirming that it works. The key point here is to make sure the nii files are encoded in "LAS" system in naming convention used by NiBabel 
 (3-Letter "To" Name), or "RPI" (3-Letter "From" Name) in ITK-Snap or C3D. I have included some documents on this in the quick-start note. 

Here is a very good article that explains the orientation encoding system used in MRI/CT volumes and why it is important: http://www.grahamwideman.com/gw/brain/orientation/orientterms.htm. Also, check the NiBabel document for image voxel orientation: https://nipy.org/nibabel/image_orientation.html.

Hope these can help.
