### ISSUE TITLE
run with erro

### ISSUE THREAD

**Issue by Dacy34** [MASILab/S-EFOV#3]
Dear developers,

Congratulations on your article being published in Radiology! I'm very interested in your work on using AI for automatic muscle segmentation in your article. 

I've pulled the image according to your QUICK_START.md file on Windows, but I've been encountering errors during subsequent runs. I'm not sure what the issue might be. I'm still relatively new to Docker and was wondering if you could update the QUICK_START.md for Windows users when you have the chance. 

Thank you very much! Wishing you success with your future work and publications in even better journals!

```
(base) PS C:\WINDOWS\system32> docker version
Client:
 Cloud integration: v1.0.35+desktop.10
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:13:02 2024
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.27.2 (137060)
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:14:25 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
(base) PS C:\WINDOWS\system32> docker run -it
>>   --gpus '"device=0"'
>>   --rm
>>   -v ${E:/bodyAI/TCIA_demo/Input}:/Input:ro -v ${E:/bodyAI/TCIA_demo/Output}:/Output
>>   -u "$(id -u):$(id -g)"
>>   masidocker/public:lung_body_composition_v1.0.3
>>   /app/src/Scripts/docker.sh
所在位置 行:2 字符: 5
+   --gpus '"device=0"'
+     ~
一元运算符“--”后面缺少表达式。
所在位置 行:2 字符: 5
+   --gpus '"device=0"'
+     ~~~~
表达式或语句中包含意外的标记“gpus”。
所在位置 行:3 字符: 5
+   --rm
+     ~
一元运算符“--”后面缺少表达式。
所在位置 行:3 字符: 5
+   --rm
+     ~~
表达式或语句中包含意外的标记“rm”。
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingExpressionAfterOperator

(base) PS C:\WINDOWS\system32> docker run -it masidocker/public:lung_body_composition_v1.0.3
root@3df0b33e8dca:/app# docker ps -a
bash: docker: command not found
root@3df0b33e8dca:/app# exit
```

**Comment by zkan12** [comment]
It seems like you lack understanding of Docker usage.” root@3df0b33e8dca:“indicates that you are already inside the container. All you need to do is run the shell script. Docker is not installed inside the container, hence running "docker ps -a" will not produce any output.

**Comment by zkan12** [comment]
It seems like you lack understanding of Docker usage.” root@3df0b33e8dca:“indicates that you are already inside the container. All you need to do is run the shell script. Docker is not installed inside the container, hence running "docker ps -a" will not produce any output.

**Comment by Dacy34** [comment]
Thank you very much for your reply! I will study docker carefully and then try it again! good luck!

**Comment by kwxu** [comment]
Hi @Dacy34! Thank you so much for your interest in our study. Unfortunately, the pipeline is only validated on Linux platforms (Ubuntu) at our site. However, we noticed that someone had adapted the pipeline on a Windows platform ([link to comment](https://github.com/MASILab/S-EFOV/issues/1#issuecomment-1785793416)). Hope this can help.

**Comment by Dacy34** [comment]
@kwxu 
OK! Thanks for your reminder! I‘ll read it carefully and give it a try！
Thank you for your reply! I hope your team will publish more high impact factor articles!
